class Entidad:
    nombre = ''
    dg = 0
    alineamiento = ''
    tipo = ''
    tamanio = ''
    iniciativa = 0
    velocidad = 0
    ataque_base = 0
    presa = 0
    ataques = None
    espacio = 0
    alcance = 0
    aptitudes = []
    cualidades = []
    ts_fort = 0
    ts_Ref = 0
    ts_vol = 0
    caracteristicas = [0, 0, 0, 0, 0, 0]
    hablidades = []
    dotes = []
    equipo = {}
    armas = []
    armadura = []
    escudo = []
    ca = 0
    toque = 0
    desprevenido = 0
    dinero = {'ppt': 0, 'po': 0, 'pp': 0, 'pc': 0}
